apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: littlelink-secure
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("links.philipkrueck.com")
      services:
        - name: littlelink
          port: 3000
  tls:
    secretName: littlelink-crt
