apiVersion: v1
data:
  credentials.json: ENC[AES256_GCM,data:rdMbPE06SgiwjyNn36EYS4KXqCxI/aZYQVNqDA8mvTkvg5feUyCoCjsCRTFDHimsNOsjYyexVJVr8U0tNCDwd+44NXKghJsi4iOcX0MqCRLHi4LWTr5UptIvmIh2+O3pvUOsEvZ0yAgj6wPZbGovd8nCX00GJEWLq91AToHGyplkx+n+bWLGrYANCPwAhn7Xtmmz8ria6Cft8a/SQ/1e6Q+jR5bcHxKiMI4bQ+p2IbDn18f9q2E3lVUwnj7unDhcJ7C5X9T3/hFMsJa7OHCUwMy3wQP4NN1WlXbt0wpw/6Q7KGqoI4jI9lOnKMA=,iv:a4m8A5eQO06wfHpbA/Fny3wDkY0GmI77f5ahi6iic80=,tag:XAgFMSkQV9P0+mqIeRi7jA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: audiobookshelf
sops:
  age:
    - recipient: age1vf5v73hyx36z3y398l2n7pxyhznptpl00kkxnuup4vrtnsjpg5tqcperyn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZER2VW9wTnZ5TXhCMXcv
        K2VQNHZPZDJJdTVXemcwRnNmWEN6YkFTMW1VCjZoU3NKSU5WOG85MU9tVXE0SEdW
        T1c3YVU2SHpUbHJsa0gvclFRVHlxVGcKLS0tIHlxMjRLdkExa0JLUlB3V05vQmhG
        RlZ3K2xVT2lGamhGbys1WHhtSGZHNTgKKAhkkk6PStY+dFEasGvVXa/SWL6hucAD
        B3XrPP3Ri2NJOUcdpXszie/7SILT3cqrY6HprOcn9p8IzcrJup9O3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T13:09:52Z"
  mac: ENC[AES256_GCM,data:gDm6/EEbK4J2y30Y7J+O5ZK9lxBrj7mEpbWmoCEoF7jLOolEfIp9kQjxjBjKML72h7j5yVvkMd7N7/Jc7kW28bSroOaueQFCBw9T3RO393R9hOW3i5b6C6uA8DdFobM7CXu+NS4gB9688F/UkTyIK78Q7wwWNafwgvBnCi+/vms=,iv:Y9JXcC0gUfEQtcabOnVzFyMbBzvllEmevGD0U9nID8g=,tag:4IH01I4ekOYXj9GbV+HMzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
