apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsUser: 1000 # node user ID
        runAsGroup: 1000 # node group ID
        fsGroup: 1000 # node group ID
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.21.0
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap

          volumeMounts:
            - name: audiobooks-volume
              mountPath: /audiobooks
            - name: podcasts-volume
              mountPath: /podcasts
            - name: config-volume
              mountPath: /config
            - name: metadata-volume
              mountPath: /metadata
          securityContext:
            allowPrivilegeEscalation: false
          # envFrom:
          #   - secretRef:
          #       name: linkding-container-env
      volumes:
        - name: audiobooks-volume
          persistentVolumeClaim:
            claimName: audiobooks-pvc
        - name: podcasts-volume
          persistentVolumeClaim:
            claimName: podcasts-pvc
        - name: config-volume
          persistentVolumeClaim:
            claimName: config-pvc
        - name: metadata-volume
          persistentVolumeClaim:
            claimName: metadata-pvc
