apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - container-env-secret.yaml
  # - cloudflare.yaml
  - cloudflare-secret.yaml
  - ingress.yaml
