apiVersion: v1
data:
  linkding-password: ENC[AES256_GCM,data:u2OfhrkEu/C2f0jymvASiw==,iv:39tOPJYN1CM7tLV+UDK2xx0i7N3sGgATvd2itVSn5fg=,tag:A7Q6LeqH32OxcfWMjH3NFw==,type:str]
  linkding-username: ENC[AES256_GCM,data:Q3be1tjyjwY=,iv:j0OvT/vRsMn0zu1FS6ifFTTbt0hSMAG8V1hM86ZnAsg=,tag:Lu5VeHGvbj2jcfd0kyQmTw==,type:str]
kind: Secret
metadata:
  name: linkding-user
  namespace: linkding
sops:
  age:
    - recipient: age1vf5v73hyx36z3y398l2n7pxyhznptpl00kkxnuup4vrtnsjpg5tqcperyn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNS8wWEhUWCtQQlY0TUhS
        enhHUVJCNEtnaU9hSHIxWUZPcWtCeXIvcmpvCmRRbmdETUQyclovbTlsZ25Gcmlo
        MjlsWVdxcnJicFlRMlU5c3hpU2I1V1EKLS0tIHFVNS9HVTVMaEN1akFHSksxbUxh
        OVZTdHB2Zm5WNTJZeFhpK3VkZUdObDQK1+n4fT/kjBpij0AImnp8Xb1dQCZIIDw0
        fa5gt87RjdH1/M0HrK7Gnas2SCAzbfGyOhDHy+i4COh1Uowdye9jUQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-06T16:39:38Z"
  mac: ENC[AES256_GCM,data:guo7fITiEpksc9L7gQXb2VEkNL/n4mBT9gdKk5TrPlGFSCa1go80nXmQcrtCqJBRx7LW9YeCJB7VZIwwIZ2x7G+2TvKigkOK9F49+aJ4XIGjpx7/0Os3BngYG8uQ3bzVfqQBeTxN7OcOf+HzuDUyRcp4qUQgc7fRQ5lRBJuiMf8=,iv:98NYL+rD0vSBEutesEsLqa2HaBsg6Px8j5hiQDxfbnY=,tag:D088+g7bM61HEd6atDLqzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
