apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheues
spec:
  dnsNames:
    - "prometheus.philipkrueck.com"
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: prometheus-crt
