apiVersion: apps/v1
kind: Deployment
metadata:
  name: solstamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solstamp
  template:
    metadata:
      labels:
        app: solstamp
    spec:
      containers:
        # - name: solstamp
        #   image: ghcr.io/philipkrueck/solstamp:v1.0.0
        #   ports:
        #     - containerPort: 3000
        - name: solstamp
          image: ghcr.io/solstamp-io/backend:v0.0.1
          ports:
            - containerPort: 3001
