apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  HOMEPAGE_ALLOWED_HOSTS: "*"
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - GH Repos:
        - Github Home:
            - href: https://github.com/philipkrueck
        - Github Homelab:
            - href: https://github.com/philipkrueck/homelab
        - Dotfiles:
            - href: https://github.com/philipkrueck/.dotfiles

  services.yaml: |
    - Applications:
        - Website:
            href: https://philipkrueck.com
            description: My website
        - solstamp.io:
            href: https://solstamp.io

    - Infrastructure:
        - Traefik:
            href: https://traefik.dashboard.philipkrueck.com
        - Grafana:
            href: https://grafana.philipkrueck.com
        - Prometheus:
            href: https://prometheus.philipkrueck.com

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: false
        cpu: true
        memory: true
        network: default
  docker.yaml: ""
