apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  HOMEPAGE_ALLOWED_HOSTS: "*"
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - homelab:
            - href: https://github.com/philipkrueck/homelab
              icon: github.png
        - .dotfiles:
            - href: https://github.com/philipkrueck/.dotfiles
              icon: github.png
    - Network:
        - LinkedIn:
            - href: https://linkedin.com/philipkrueck
              icon: linkedin.png
        - X:
            - href: https://x.com
              icon: x.png

  services.yaml: |
    - Applications:
        - philipkrueck.com:
            href: https://philipkrueck.com
            ping: philipkrueck.com
        - solstamp.io:
            href: https://solstamp.io
            ping: solstamp.io

    - Infrastructure:
        - Traefik:
            icon: traefik.png
            href: https://dashboard.traefik.philipkrueck.com
            ping: solstamp.io
        - Grafana:
            icon: grafana.png
            href: https://grafana.philipkrueck.com
        - Prometheus:
            icon: prometheus.png
            href: https://prometheus.philipkrueck.com

  docker.yaml: ""
