# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: grafana
# spec:
#   dnsNames:
#     - "grafana.philipkrueck.com"
#   issuerRef:
#     kind: ClusterIssuer
#     name: cluster-issuer
#   secretName: grafana-crt
