apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website
spec:
  dnsNames:
    - "philipkrueck.com"
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: website-crt
