apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-secure
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host("grafana.philipkrueck.com")
      services:
        - name: grafana
          port: 3000
  tls:
    secretName: grafana-crt
